from selenium import webdriver

driver=webdriver.Chrome()
driver.maximize_window()
driver.get("http://consolebeta.vertoz.com/index.html")
username=driver.find_element_by_id("Emailid")
username.send_keys("alliance@vertoz.com")
passwrd=driver.find_element_by_id("password")
passwrd.send_keys("vertoz$123")
login=driver.find_element_by_id("Login")
login.click()
driver.implicitly_wait(30)
adunit=driver.find_element_by_id("vertozmenu4")
driver.implicitly_wait(20)
adunit.click()
driver.implicitly_wait(20)

#new_adunit = driver.find_elements_by_xpath("//*[@id='vertozmenu4']/ul/li[2]/a[2]")
new_adunit = driver.find_element_by_link_text("Ad Unit Management")
print("successful")
new_adunit.click()
driver.implicitly_wait(20)
create_adunit = driver.find_element_by_link_text("+ Add New Ad Unit")
create_adunit.click()
client=driver.find_element_by_id("newclientdropdown")
client.clear()
#client.send_keys("s//*[@id="ClientListes"]/div/div/ul/li[4]/a")
site=driver.find_element_by_id("website")
site.clear()
#site.send_keys("//*[@id="WebList"]/div/ul/li[3]/a")
adsize=driver.find_element_by_id("square-300x250")
adsize.click()
submit=driver.find_element_by_id("PageAds")
submit.click()
